name: Serialize AMP to PFP-CIDOC

on:
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
      - name: dump the data
        run: ./scripts/build_amp_graph.sh
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: AMP entity data PFP-CIDOC serialization