name: Serialize AMP to PFP-CIDOC

on:
  workflow_dispatch:

jobs:
  download:
    name: serialize AMP to PFP-CIDOC
    runs-on: ubuntu-latest
    env:
      OWNCLOUD_USER: ${{ secrets.OWNCLOUD_USER }}
      OWNCLOUD_PW: ${{ secrets.OWNCLOUD_PW }}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
      - name: dump the data
        run: ./scripts/build_graph.sh
      - name: validate
        run: ./scripts/validate.sh
      - uses: actions/upload-artifact@v4
        with:
          name: validation_report.txt
          path: datasets/validation_report.txt
      - name: upload to ownCloud
        run: python scripts/upload.py