name: Serialize AMP to PFP-CIDOC

on:
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
      OWNCLOUD_USER: ${{ secrets.OWNCLOUD_USER }}
      OWNCLOUD_PASSWORD: ${{ secrets.OWNCLOUD_PASSWORD }}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
      - name: dump the data
        run: ./scripts/build_amp_graph.sh